groups:
  - name: feed_processor_alerts
    rules:
      # Pipeline Health
      - alert: PipelineStalled
        expr: rate(pipeline_items_processed_total{status="stored"}[5m]) == 0
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "Pipeline is stalled"
          description: "No items have been processed in the last 5 minutes"

      # Error Rate
      - alert: HighErrorRate
        expr: |
          sum(rate(pipeline_items_processed_total{status=~".*error"}[5m]))
          /
          sum(rate(pipeline_items_processed_total[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 10% in the last 5 minutes"

      # Queue Size
      - alert: QueueOverflow
        expr: pipeline_queue_size > 5000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Queue size too large"
          description: "Queue size has exceeded 5000 items"

      # Processing Latency
      - alert: HighProcessingLatency
        expr: histogram_quantile(0.95, rate(pipeline_processing_duration_seconds_bucket[5m])) > 30
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High processing latency"
          description: "95th percentile of processing duration is above 30 seconds"

      # Resource Usage
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / (1024 * 1024) > 900
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 900MB"

      # Notification System
      - alert: NotificationFailures
        expr: rate(notification_errors_total[5m]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Notification system failures"
          description: "Errors detected in the notification system"
