global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"

scrape_configs:
  - job_name: 'feed-processor'
    static_configs:
      - targets: ['feed-processor:9090']
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 5s
