name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.12"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel setuptools
        
    - name: Install package
      run: |
        pip install -e ".[dev]"
        
    - name: Format with black
      run: |
        black feed_processor tests --check || (black feed_processor tests && git config --global user.email "action@github.com" && git config --global user.name "GitHub Action" && git add . && git commit -m "style: Format code with black" && git push)
        
    - name: Check imports with isort
      run: isort --check-only feed_processor tests

    - name: Lint with flake8
      run: flake8 feed_processor tests

    - name: Type check with mypy
      run: mypy feed_processor

  test:
    runs-on: ubuntu-latest
    needs: lint
    services:
      prometheus:
        image: prom/prometheus:latest
        ports:
          - 9090:9090
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel setuptools
        
    - name: Install package
      run: |
        pip install -e ".[test]"
        
    - name: Run tests
      run: |
        pytest tests/ --cov=feed_processor --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
